ports:
- port: 8050 # Dash
  onOpen: open-preview

tasks:
  - init: |
      sed -i '/dash-/d' requires-install.txt
      pip install -e . --no-cache-dir -r requires-install.txt -r requires-dev.txt -r requires-testing.txt --progress-bar off
      mkdir packages
      git clone --depth 1 https://github.com/plotly/dash-core-components.git
      cd dash-core-components && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/  && cd ..
      ls -la packages
      git clone --depth 1 https://github.com/plotly/dash-table.git
      cd dash-table && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/ && cd ..
      git clone --depth 1 https://github.com/plotly/dash-html-components.git
      cd dash-html-components && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/ && cd ..
      ls -la packages
  - command:
      python setup.py sdist

# You should be able to install dash with:
# pip install dist/dash-1.20.0.tar.gz
